version: "3.8"

services:
  workspace-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/workspacedb
      - JWT_SECRET=clave_secreta
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workspacedb
    ports:
      - "5432:5432"
